name: Generate snake animation

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate snake animation from GitHub user profile
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake-light.svg?palette=github-light
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy snake animation to gh-pages branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: dist
          commit_message: "Deploy snake animation"
